// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface DistributionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.DistributionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Key_Name = 1;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string Key_Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>float percentile = 2;</code>
   */
  float getPercentile();
}
