// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface InventoryRecordsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.InventoryRecords)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .inventory.InventoryRecord records = 1;</code>
   */
  java.util.List<inventory.grpc.InventoryRecord> 
      getRecordsList();
  /**
   * <code>repeated .inventory.InventoryRecord records = 1;</code>
   */
  inventory.grpc.InventoryRecord getRecords(int index);
  /**
   * <code>repeated .inventory.InventoryRecord records = 1;</code>
   */
  int getRecordsCount();
  /**
   * <code>repeated .inventory.InventoryRecord records = 1;</code>
   */
  java.util.List<? extends inventory.grpc.InventoryRecordOrBuilder> 
      getRecordsOrBuilderList();
  /**
   * <code>repeated .inventory.InventoryRecord records = 1;</code>
   */
  inventory.grpc.InventoryRecordOrBuilder getRecordsOrBuilder(
      int index);
}
