// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public final class Inventory {
  private Inventory() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_InventoryRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_InventoryRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_InventoryRecords_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_InventoryRecords_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_PercentileValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_PercentileValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_SearchByIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_SearchByIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_SearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_SearchInRangeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_SearchInRangeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_inventory_DistributionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_inventory_DistributionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025InventoryRecord.proto\022\tinventory\"\272\001\n\017I" +
      "nventoryRecord\022\013\n\003SKU\030\001 \001(\t\022\023\n\013DESCRIPTI" +
      "ON\030\002 \001(\t\022\013\n\003BIN\030\003 \001(\t\022\020\n\010LOCATION\030\004 \001(\t\022" +
      "\014\n\004UNIT\030\005 \001(\t\022\013\n\003QTY\030\006 \001(\002\022\023\n\013REORDER_QT" +
      "Y\030\007 \001(\002\022\014\n\004COST\030\010 \001(\002\022\027\n\017INVENTORY_VALUE" +
      "\030\t \001(\002\022\017\n\007REORDER\030\n \001(\010\"?\n\020InventoryReco" +
      "rds\022+\n\007records\030\001 \003(\0132\032.inventory.Invento" +
      "ryRecord\"+\n\017PercentileValue\022\030\n\020percentil" +
      "e_value\030\001 \001(\002\" \n\021SearchByIDRequest\022\013\n\003SK" +
      "U\030\001 \001(\t\"4\n\rSearchRequest\022\020\n\010Key_Name\030\001 \001" +
      "(\t\022\021\n\tKey_Value\030\002 \001(\t\"X\n\024SearchInRangeRe" +
      "quest\022\020\n\010Key_Name\030\001 \001(\t\022\027\n\017Key_Value_sta" +
      "rt\030\002 \001(\t\022\025\n\rKey_Value_end\030\003 \001(\t\";\n\023Distr" +
      "ibutionRequest\022\020\n\010Key_Name\030\001 \001(\t\022\022\n\nperc" +
      "entile\030\002 \001(\0022\262\002\n\tinventory\022F\n\nsearchByID" +
      "\022\034.inventory.SearchByIDRequest\032\032.invento" +
      "ry.InventoryRecord\022?\n\006search\022\030.inventory" +
      ".SearchRequest\032\033.inventory.InventoryReco" +
      "rds\022M\n\rsearchInRange\022\037.inventory.SearchI" +
      "nRangeRequest\032\033.inventory.InventoryRecor" +
      "ds\022M\n\017getDistribution\022\036.inventory.Distri" +
      "butionRequest\032\032.inventory.PercentileValu" +
      "eB\035\n\016inventory.grpcB\tInventoryP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_inventory_InventoryRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_inventory_InventoryRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_InventoryRecord_descriptor,
        new java.lang.String[] { "SKU", "DESCRIPTION", "BIN", "LOCATION", "UNIT", "QTY", "REORDERQTY", "COST", "INVENTORYVALUE", "REORDER", });
    internal_static_inventory_InventoryRecords_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_inventory_InventoryRecords_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_InventoryRecords_descriptor,
        new java.lang.String[] { "Records", });
    internal_static_inventory_PercentileValue_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_inventory_PercentileValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_PercentileValue_descriptor,
        new java.lang.String[] { "PercentileValue", });
    internal_static_inventory_SearchByIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_inventory_SearchByIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_SearchByIDRequest_descriptor,
        new java.lang.String[] { "SKU", });
    internal_static_inventory_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_inventory_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_SearchRequest_descriptor,
        new java.lang.String[] { "KeyName", "KeyValue", });
    internal_static_inventory_SearchInRangeRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_inventory_SearchInRangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_SearchInRangeRequest_descriptor,
        new java.lang.String[] { "KeyName", "KeyValueStart", "KeyValueEnd", });
    internal_static_inventory_DistributionRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_inventory_DistributionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_inventory_DistributionRequest_descriptor,
        new java.lang.String[] { "KeyName", "Percentile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
