// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface InventoryRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.InventoryRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SKU = 1;</code>
   */
  java.lang.String getSKU();
  /**
   * <code>string SKU = 1;</code>
   */
  com.google.protobuf.ByteString
      getSKUBytes();

  /**
   * <code>string DESCRIPTION = 2;</code>
   */
  java.lang.String getDESCRIPTION();
  /**
   * <code>string DESCRIPTION = 2;</code>
   */
  com.google.protobuf.ByteString
      getDESCRIPTIONBytes();

  /**
   * <code>string BIN = 3;</code>
   */
  java.lang.String getBIN();
  /**
   * <code>string BIN = 3;</code>
   */
  com.google.protobuf.ByteString
      getBINBytes();

  /**
   * <code>string LOCATION = 4;</code>
   */
  java.lang.String getLOCATION();
  /**
   * <code>string LOCATION = 4;</code>
   */
  com.google.protobuf.ByteString
      getLOCATIONBytes();

  /**
   * <code>string UNIT = 5;</code>
   */
  java.lang.String getUNIT();
  /**
   * <code>string UNIT = 5;</code>
   */
  com.google.protobuf.ByteString
      getUNITBytes();

  /**
   * <code>int32 QTY = 6;</code>
   */
  int getQTY();

  /**
   * <code>int32 REORDER_QTY = 7;</code>
   */
  int getREORDERQTY();

  /**
   * <code>float COST = 8;</code>
   */
  float getCOST();

  /**
   * <code>float INVENTORY_VALUE = 9;</code>
   */
  float getINVENTORYVALUE();

  /**
   * <code>bool REORDER = 10;</code>
   */
  boolean getREORDER();
}
