// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

/**
 * Protobuf type {@code inventory.InventoryRecord}
 */
public  final class InventoryRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:inventory.InventoryRecord)
    InventoryRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InventoryRecord.newBuilder() to construct.
  private InventoryRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InventoryRecord() {
    sKU_ = "";
    dESCRIPTION_ = "";
    bIN_ = "";
    lOCATION_ = "";
    uNIT_ = "";
    qTY_ = 0;
    rEORDERQTY_ = 0;
    cOST_ = 0F;
    iNVENTORYVALUE_ = 0F;
    rEORDER_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InventoryRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            sKU_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dESCRIPTION_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            bIN_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            lOCATION_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            uNIT_ = s;
            break;
          }
          case 48: {

            qTY_ = input.readInt32();
            break;
          }
          case 56: {

            rEORDERQTY_ = input.readInt32();
            break;
          }
          case 69: {

            cOST_ = input.readFloat();
            break;
          }
          case 77: {

            iNVENTORYVALUE_ = input.readFloat();
            break;
          }
          case 80: {

            rEORDER_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return inventory.grpc.Inventory.internal_static_inventory_InventoryRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return inventory.grpc.Inventory.internal_static_inventory_InventoryRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            inventory.grpc.InventoryRecord.class, inventory.grpc.InventoryRecord.Builder.class);
  }

  public static final int SKU_FIELD_NUMBER = 1;
  private volatile java.lang.Object sKU_;
  /**
   * <code>string SKU = 1;</code>
   */
  public java.lang.String getSKU() {
    java.lang.Object ref = sKU_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sKU_ = s;
      return s;
    }
  }
  /**
   * <code>string SKU = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSKUBytes() {
    java.lang.Object ref = sKU_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sKU_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private volatile java.lang.Object dESCRIPTION_;
  /**
   * <code>string DESCRIPTION = 2;</code>
   */
  public java.lang.String getDESCRIPTION() {
    java.lang.Object ref = dESCRIPTION_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dESCRIPTION_ = s;
      return s;
    }
  }
  /**
   * <code>string DESCRIPTION = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDESCRIPTIONBytes() {
    java.lang.Object ref = dESCRIPTION_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dESCRIPTION_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIN_FIELD_NUMBER = 3;
  private volatile java.lang.Object bIN_;
  /**
   * <code>string BIN = 3;</code>
   */
  public java.lang.String getBIN() {
    java.lang.Object ref = bIN_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bIN_ = s;
      return s;
    }
  }
  /**
   * <code>string BIN = 3;</code>
   */
  public com.google.protobuf.ByteString
      getBINBytes() {
    java.lang.Object ref = bIN_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bIN_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION_FIELD_NUMBER = 4;
  private volatile java.lang.Object lOCATION_;
  /**
   * <code>string LOCATION = 4;</code>
   */
  public java.lang.String getLOCATION() {
    java.lang.Object ref = lOCATION_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lOCATION_ = s;
      return s;
    }
  }
  /**
   * <code>string LOCATION = 4;</code>
   */
  public com.google.protobuf.ByteString
      getLOCATIONBytes() {
    java.lang.Object ref = lOCATION_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lOCATION_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UNIT_FIELD_NUMBER = 5;
  private volatile java.lang.Object uNIT_;
  /**
   * <code>string UNIT = 5;</code>
   */
  public java.lang.String getUNIT() {
    java.lang.Object ref = uNIT_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uNIT_ = s;
      return s;
    }
  }
  /**
   * <code>string UNIT = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUNITBytes() {
    java.lang.Object ref = uNIT_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uNIT_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QTY_FIELD_NUMBER = 6;
  private int qTY_;
  /**
   * <code>int32 QTY = 6;</code>
   */
  public int getQTY() {
    return qTY_;
  }

  public static final int REORDER_QTY_FIELD_NUMBER = 7;
  private int rEORDERQTY_;
  /**
   * <code>int32 REORDER_QTY = 7;</code>
   */
  public int getREORDERQTY() {
    return rEORDERQTY_;
  }

  public static final int COST_FIELD_NUMBER = 8;
  private float cOST_;
  /**
   * <code>float COST = 8;</code>
   */
  public float getCOST() {
    return cOST_;
  }

  public static final int INVENTORY_VALUE_FIELD_NUMBER = 9;
  private float iNVENTORYVALUE_;
  /**
   * <code>float INVENTORY_VALUE = 9;</code>
   */
  public float getINVENTORYVALUE() {
    return iNVENTORYVALUE_;
  }

  public static final int REORDER_FIELD_NUMBER = 10;
  private boolean rEORDER_;
  /**
   * <code>bool REORDER = 10;</code>
   */
  public boolean getREORDER() {
    return rEORDER_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSKUBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sKU_);
    }
    if (!getDESCRIPTIONBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dESCRIPTION_);
    }
    if (!getBINBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bIN_);
    }
    if (!getLOCATIONBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lOCATION_);
    }
    if (!getUNITBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, uNIT_);
    }
    if (qTY_ != 0) {
      output.writeInt32(6, qTY_);
    }
    if (rEORDERQTY_ != 0) {
      output.writeInt32(7, rEORDERQTY_);
    }
    if (cOST_ != 0F) {
      output.writeFloat(8, cOST_);
    }
    if (iNVENTORYVALUE_ != 0F) {
      output.writeFloat(9, iNVENTORYVALUE_);
    }
    if (rEORDER_ != false) {
      output.writeBool(10, rEORDER_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSKUBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sKU_);
    }
    if (!getDESCRIPTIONBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dESCRIPTION_);
    }
    if (!getBINBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bIN_);
    }
    if (!getLOCATIONBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lOCATION_);
    }
    if (!getUNITBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, uNIT_);
    }
    if (qTY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, qTY_);
    }
    if (rEORDERQTY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, rEORDERQTY_);
    }
    if (cOST_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(8, cOST_);
    }
    if (iNVENTORYVALUE_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(9, iNVENTORYVALUE_);
    }
    if (rEORDER_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, rEORDER_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof inventory.grpc.InventoryRecord)) {
      return super.equals(obj);
    }
    inventory.grpc.InventoryRecord other = (inventory.grpc.InventoryRecord) obj;

    boolean result = true;
    result = result && getSKU()
        .equals(other.getSKU());
    result = result && getDESCRIPTION()
        .equals(other.getDESCRIPTION());
    result = result && getBIN()
        .equals(other.getBIN());
    result = result && getLOCATION()
        .equals(other.getLOCATION());
    result = result && getUNIT()
        .equals(other.getUNIT());
    result = result && (getQTY()
        == other.getQTY());
    result = result && (getREORDERQTY()
        == other.getREORDERQTY());
    result = result && (
        java.lang.Float.floatToIntBits(getCOST())
        == java.lang.Float.floatToIntBits(
            other.getCOST()));
    result = result && (
        java.lang.Float.floatToIntBits(getINVENTORYVALUE())
        == java.lang.Float.floatToIntBits(
            other.getINVENTORYVALUE()));
    result = result && (getREORDER()
        == other.getREORDER());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SKU_FIELD_NUMBER;
    hash = (53 * hash) + getSKU().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDESCRIPTION().hashCode();
    hash = (37 * hash) + BIN_FIELD_NUMBER;
    hash = (53 * hash) + getBIN().hashCode();
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLOCATION().hashCode();
    hash = (37 * hash) + UNIT_FIELD_NUMBER;
    hash = (53 * hash) + getUNIT().hashCode();
    hash = (37 * hash) + QTY_FIELD_NUMBER;
    hash = (53 * hash) + getQTY();
    hash = (37 * hash) + REORDER_QTY_FIELD_NUMBER;
    hash = (53 * hash) + getREORDERQTY();
    hash = (37 * hash) + COST_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCOST());
    hash = (37 * hash) + INVENTORY_VALUE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getINVENTORYVALUE());
    hash = (37 * hash) + REORDER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getREORDER());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static inventory.grpc.InventoryRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static inventory.grpc.InventoryRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static inventory.grpc.InventoryRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static inventory.grpc.InventoryRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static inventory.grpc.InventoryRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static inventory.grpc.InventoryRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static inventory.grpc.InventoryRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static inventory.grpc.InventoryRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static inventory.grpc.InventoryRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static inventory.grpc.InventoryRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static inventory.grpc.InventoryRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static inventory.grpc.InventoryRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(inventory.grpc.InventoryRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code inventory.InventoryRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:inventory.InventoryRecord)
      inventory.grpc.InventoryRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return inventory.grpc.Inventory.internal_static_inventory_InventoryRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return inventory.grpc.Inventory.internal_static_inventory_InventoryRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              inventory.grpc.InventoryRecord.class, inventory.grpc.InventoryRecord.Builder.class);
    }

    // Construct using inventory.grpc.InventoryRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      sKU_ = "";

      dESCRIPTION_ = "";

      bIN_ = "";

      lOCATION_ = "";

      uNIT_ = "";

      qTY_ = 0;

      rEORDERQTY_ = 0;

      cOST_ = 0F;

      iNVENTORYVALUE_ = 0F;

      rEORDER_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return inventory.grpc.Inventory.internal_static_inventory_InventoryRecord_descriptor;
    }

    @java.lang.Override
    public inventory.grpc.InventoryRecord getDefaultInstanceForType() {
      return inventory.grpc.InventoryRecord.getDefaultInstance();
    }

    @java.lang.Override
    public inventory.grpc.InventoryRecord build() {
      inventory.grpc.InventoryRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public inventory.grpc.InventoryRecord buildPartial() {
      inventory.grpc.InventoryRecord result = new inventory.grpc.InventoryRecord(this);
      result.sKU_ = sKU_;
      result.dESCRIPTION_ = dESCRIPTION_;
      result.bIN_ = bIN_;
      result.lOCATION_ = lOCATION_;
      result.uNIT_ = uNIT_;
      result.qTY_ = qTY_;
      result.rEORDERQTY_ = rEORDERQTY_;
      result.cOST_ = cOST_;
      result.iNVENTORYVALUE_ = iNVENTORYVALUE_;
      result.rEORDER_ = rEORDER_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof inventory.grpc.InventoryRecord) {
        return mergeFrom((inventory.grpc.InventoryRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(inventory.grpc.InventoryRecord other) {
      if (other == inventory.grpc.InventoryRecord.getDefaultInstance()) return this;
      if (!other.getSKU().isEmpty()) {
        sKU_ = other.sKU_;
        onChanged();
      }
      if (!other.getDESCRIPTION().isEmpty()) {
        dESCRIPTION_ = other.dESCRIPTION_;
        onChanged();
      }
      if (!other.getBIN().isEmpty()) {
        bIN_ = other.bIN_;
        onChanged();
      }
      if (!other.getLOCATION().isEmpty()) {
        lOCATION_ = other.lOCATION_;
        onChanged();
      }
      if (!other.getUNIT().isEmpty()) {
        uNIT_ = other.uNIT_;
        onChanged();
      }
      if (other.getQTY() != 0) {
        setQTY(other.getQTY());
      }
      if (other.getREORDERQTY() != 0) {
        setREORDERQTY(other.getREORDERQTY());
      }
      if (other.getCOST() != 0F) {
        setCOST(other.getCOST());
      }
      if (other.getINVENTORYVALUE() != 0F) {
        setINVENTORYVALUE(other.getINVENTORYVALUE());
      }
      if (other.getREORDER() != false) {
        setREORDER(other.getREORDER());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      inventory.grpc.InventoryRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (inventory.grpc.InventoryRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object sKU_ = "";
    /**
     * <code>string SKU = 1;</code>
     */
    public java.lang.String getSKU() {
      java.lang.Object ref = sKU_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sKU_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string SKU = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSKUBytes() {
      java.lang.Object ref = sKU_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sKU_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string SKU = 1;</code>
     */
    public Builder setSKU(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sKU_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string SKU = 1;</code>
     */
    public Builder clearSKU() {
      
      sKU_ = getDefaultInstance().getSKU();
      onChanged();
      return this;
    }
    /**
     * <code>string SKU = 1;</code>
     */
    public Builder setSKUBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sKU_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dESCRIPTION_ = "";
    /**
     * <code>string DESCRIPTION = 2;</code>
     */
    public java.lang.String getDESCRIPTION() {
      java.lang.Object ref = dESCRIPTION_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dESCRIPTION_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string DESCRIPTION = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDESCRIPTIONBytes() {
      java.lang.Object ref = dESCRIPTION_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dESCRIPTION_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string DESCRIPTION = 2;</code>
     */
    public Builder setDESCRIPTION(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dESCRIPTION_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string DESCRIPTION = 2;</code>
     */
    public Builder clearDESCRIPTION() {
      
      dESCRIPTION_ = getDefaultInstance().getDESCRIPTION();
      onChanged();
      return this;
    }
    /**
     * <code>string DESCRIPTION = 2;</code>
     */
    public Builder setDESCRIPTIONBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dESCRIPTION_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bIN_ = "";
    /**
     * <code>string BIN = 3;</code>
     */
    public java.lang.String getBIN() {
      java.lang.Object ref = bIN_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bIN_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string BIN = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBINBytes() {
      java.lang.Object ref = bIN_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bIN_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string BIN = 3;</code>
     */
    public Builder setBIN(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bIN_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string BIN = 3;</code>
     */
    public Builder clearBIN() {
      
      bIN_ = getDefaultInstance().getBIN();
      onChanged();
      return this;
    }
    /**
     * <code>string BIN = 3;</code>
     */
    public Builder setBINBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bIN_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lOCATION_ = "";
    /**
     * <code>string LOCATION = 4;</code>
     */
    public java.lang.String getLOCATION() {
      java.lang.Object ref = lOCATION_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lOCATION_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string LOCATION = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLOCATIONBytes() {
      java.lang.Object ref = lOCATION_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lOCATION_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string LOCATION = 4;</code>
     */
    public Builder setLOCATION(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lOCATION_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string LOCATION = 4;</code>
     */
    public Builder clearLOCATION() {
      
      lOCATION_ = getDefaultInstance().getLOCATION();
      onChanged();
      return this;
    }
    /**
     * <code>string LOCATION = 4;</code>
     */
    public Builder setLOCATIONBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lOCATION_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object uNIT_ = "";
    /**
     * <code>string UNIT = 5;</code>
     */
    public java.lang.String getUNIT() {
      java.lang.Object ref = uNIT_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uNIT_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string UNIT = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUNITBytes() {
      java.lang.Object ref = uNIT_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uNIT_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string UNIT = 5;</code>
     */
    public Builder setUNIT(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uNIT_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string UNIT = 5;</code>
     */
    public Builder clearUNIT() {
      
      uNIT_ = getDefaultInstance().getUNIT();
      onChanged();
      return this;
    }
    /**
     * <code>string UNIT = 5;</code>
     */
    public Builder setUNITBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uNIT_ = value;
      onChanged();
      return this;
    }

    private int qTY_ ;
    /**
     * <code>int32 QTY = 6;</code>
     */
    public int getQTY() {
      return qTY_;
    }
    /**
     * <code>int32 QTY = 6;</code>
     */
    public Builder setQTY(int value) {
      
      qTY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 QTY = 6;</code>
     */
    public Builder clearQTY() {
      
      qTY_ = 0;
      onChanged();
      return this;
    }

    private int rEORDERQTY_ ;
    /**
     * <code>int32 REORDER_QTY = 7;</code>
     */
    public int getREORDERQTY() {
      return rEORDERQTY_;
    }
    /**
     * <code>int32 REORDER_QTY = 7;</code>
     */
    public Builder setREORDERQTY(int value) {
      
      rEORDERQTY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 REORDER_QTY = 7;</code>
     */
    public Builder clearREORDERQTY() {
      
      rEORDERQTY_ = 0;
      onChanged();
      return this;
    }

    private float cOST_ ;
    /**
     * <code>float COST = 8;</code>
     */
    public float getCOST() {
      return cOST_;
    }
    /**
     * <code>float COST = 8;</code>
     */
    public Builder setCOST(float value) {
      
      cOST_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float COST = 8;</code>
     */
    public Builder clearCOST() {
      
      cOST_ = 0F;
      onChanged();
      return this;
    }

    private float iNVENTORYVALUE_ ;
    /**
     * <code>float INVENTORY_VALUE = 9;</code>
     */
    public float getINVENTORYVALUE() {
      return iNVENTORYVALUE_;
    }
    /**
     * <code>float INVENTORY_VALUE = 9;</code>
     */
    public Builder setINVENTORYVALUE(float value) {
      
      iNVENTORYVALUE_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float INVENTORY_VALUE = 9;</code>
     */
    public Builder clearINVENTORYVALUE() {
      
      iNVENTORYVALUE_ = 0F;
      onChanged();
      return this;
    }

    private boolean rEORDER_ ;
    /**
     * <code>bool REORDER = 10;</code>
     */
    public boolean getREORDER() {
      return rEORDER_;
    }
    /**
     * <code>bool REORDER = 10;</code>
     */
    public Builder setREORDER(boolean value) {
      
      rEORDER_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool REORDER = 10;</code>
     */
    public Builder clearREORDER() {
      
      rEORDER_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:inventory.InventoryRecord)
  }

  // @@protoc_insertion_point(class_scope:inventory.InventoryRecord)
  private static final inventory.grpc.InventoryRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new inventory.grpc.InventoryRecord();
  }

  public static inventory.grpc.InventoryRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InventoryRecord>
      PARSER = new com.google.protobuf.AbstractParser<InventoryRecord>() {
    @java.lang.Override
    public InventoryRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InventoryRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InventoryRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InventoryRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public inventory.grpc.InventoryRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

