// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface PercentileValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.PercentileValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float percentile_value = 1;</code>
   */
  float getPercentileValue();
}
