// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface SearchByIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.SearchByIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SKU = 1;</code>
   */
  java.lang.String getSKU();
  /**
   * <code>string SKU = 1;</code>
   */
  com.google.protobuf.ByteString
      getSKUBytes();
}
