// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface SearchInRangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.SearchInRangeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Key_Name = 1;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string Key_Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>string Key_Value_start = 2;</code>
   */
  java.lang.String getKeyValueStart();
  /**
   * <code>string Key_Value_start = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyValueStartBytes();

  /**
   * <code>string Key_Value_end = 3;</code>
   */
  java.lang.String getKeyValueEnd();
  /**
   * <code>string Key_Value_end = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyValueEndBytes();
}
