// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Key_Name = 1;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string Key_Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>string Key_Value = 2;</code>
   */
  java.lang.String getKeyValue();
  /**
   * <code>string Key_Value = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyValueBytes();
}
