// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Key_Name = 1;</code>
   */
  java.lang.String getKeyName();
  /**
   * <code>string Key_Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyNameBytes();

  /**
   * <code>string Key_Value = 2;</code>
   */
  java.lang.String getKeyValue();
  /**
   * <code>string Key_Value = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyValueBytes();

  /**
   * <code>string Val_Name = 3;</code>
   */
  java.lang.String getValName();
  /**
   * <code>string Val_Name = 3;</code>
   */
  com.google.protobuf.ByteString
      getValNameBytes();

  /**
   * <code>string Val_Val_New = 4;</code>
   */
  java.lang.String getValValNew();
  /**
   * <code>string Val_Val_New = 4;</code>
   */
  com.google.protobuf.ByteString
      getValValNewBytes();
}
