// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryRecord.proto

package inventory.grpc;

public interface UpdateRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventory.UpdateResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool updated = 1;</code>
   */
  boolean getUpdated();
}
